[server]
headless = true
address = "0.0.0.0"
port = 8080
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "light"
primaryColor = "#FF8C00"
backgroundColor = "#FFF8DC"
secondaryBackgroundColor = "#FFEFD5"
textColor = "#333333"
font = "serif"
